"""add log column to campaigns table

Revision ID: 330d3f307e27
Revises: d526fb4258b0
Create Date: 2024-04-17 19:17:54.285722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330d3f307e27'
down_revision = 'd526fb4258b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log', sa.Text(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('log')

    # ### end Alembic commands ###
