"""Initial migration.

Revision ID: 6231a55246e0
Revises: 
Create Date: 2024-04-14 15:33:24.984937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6231a55246e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('_password_hash', sa.String(length=128), nullable=True),
    sa.Column('game_master', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gamemaster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gamemaster_id'], ['users.id'], name=op.f('fk_campaigns_gamemaster_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('class_', sa.String(length=64), nullable=False),
    sa.Column('race', sa.String(length=64), nullable=False),
    sa.Column('alignment', sa.String(length=64), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('alive', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_characters_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_campaigns',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('gamemaster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_character_campaigns_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_campaigns_character_id_characters')),
    sa.ForeignKeyConstraint(['gamemaster_id'], ['users.id'], name=op.f('fk_character_campaigns_gamemaster_id_users')),
    sa.PrimaryKeyConstraint('character_id', 'campaign_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_campaigns')
    op.drop_table('characters')
    op.drop_table('campaigns')
    op.drop_table('users')
    # ### end Alembic commands ###
