"""Add cascading deletion to CharacterCampaign

Revision ID: d526fb4258b0
Revises: 1d1391c473f2
Create Date: 2024-04-17 11:59:53.809295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd526fb4258b0'
down_revision = '1d1391c473f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_campaigns', schema=None) as batch_op:
        batch_op.drop_constraint('fk_character_campaigns_character_id_characters', type_='foreignkey')
        batch_op.drop_constraint('fk_character_campaigns_campaign_id_campaigns', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_character_campaigns_campaign_id_campaigns'), 'campaigns', ['campaign_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_character_campaigns_character_id_characters'), 'characters', ['character_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_campaigns', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_character_campaigns_character_id_characters'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_character_campaigns_campaign_id_campaigns'), type_='foreignkey')
        batch_op.create_foreign_key('fk_character_campaigns_campaign_id_campaigns', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_character_campaigns_character_id_characters', 'characters', ['character_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
